---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
        - name: con
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
          env:
            - name: db
              valueFrom:
                configMapKeyRef:
                  name: devops
                  key: food



