---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myde
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
        - name: con1
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: devops

