
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myde2
spec:
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
        - name: con2
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
