---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myde
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
        - name: con3
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
