---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  parallelism: 2
  activeDeadlineSeconds: 20
  template:
    metadata:
      name: testjob
    spec:
      containers:
        - name: con1
          image: shaikmustafa/cycle
          ports:
            - containerPort: 80
          command: ["/bin/bash","-c","apt update -y ;sleep 50"]
      restartPolicy: Never
