---
apiVersion: v1
kind: Pod
metadata:
  name: newpod
  namespace: naveen
spec:
  containers:
    - name: mycon
      image: shaikmustafa/cycle
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "150m"
          memory: "12Mi"
        limits:
          cpu: "250m"
          memory: "32Mi"
