---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: con-1
      image: shaikmustafa/paytm:bus
      ports:
        - containerPort: 80
      args:
        - /bin/bash
        - -c
        - touch /tmp/healthy ; sleep 300
      livenessProbe:
        exec:
          command:
            - cat 
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 30
