---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvc
spec:
  capacity:
    storage: 5Gi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
      volumeID: vol-0f44c224e557717f4
      fsType: ext4
