---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myrole
  namespace: naveen
subjects:
  - kind: User
    name: mustafa
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: myrole
  apiGroup: rbac.authorization.k8s.io
