---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: " * * * * * "
  jobTemplate:
    spec:
      template:
        spec:
           containers:
             - name: con1
               image: shaikmustafa/cycle
               ports:
                 - containerPort: 80
               command: ["/bin/bash","-c","apt update -y "]
           restartPolicy: Never
