
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myde74
spec:
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
        - name: con66
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
