
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvpvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
       containers:
          - name: con-2345
            image: nginx
            ports:
              - containerPort: 80
            command: ["/bin/bash", "-c" , " while true; do echo my name is naveen; sleep 50 ;done"]
            volumeMounts:
              - name: devops
                mountPath: "/tmp/naveen"
       volumes:
         - name: devops
           persistentVolumeClaim:
             claimName: mypv
